### ISSUE TITLE
年代情報を取得するモジュール等の命名にdecadesを使用しているが、ageに修正

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/vook_db_v4#18]
# Todo
- [x] 変更するファイル名の特定
- [x] 変更するファイル名の変更
  - [x] .//tests/test_extract_decades_only.py
  - [x] .//tests/test_extract_decades_both.py
  - [x] .//vook_db_v4/extract_decades.py
- [x] 変数名の特定
- [x] 変数名の変更
- [x] テストの実行

# Why
- 命名の統一
