### ISSUE TITLE
#20.3 extract_itemモジュールの作成

### ISSUE THREAD

**Issue by atsushimemet** [atsushimemet/vook_db_v4#26]
# Parent issue
- #20

# Todo
- [x] test_extract_item.pyの作成
  - [x] extract_item_denim関数のテスト
  - [x] extract_item_denim_jacket関数のテスト
- [x] extract_item.pyの作成
  - [x] extract_item_denim関数の作成
  - [x] extract_item_denim_jacket関数の作成
